name: Compilar APK de Flet de Forma Automatica

on:
  push:
    branches: [ main, master, principal ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el codigo del repositorio
        uses: actions/checkout@v4

      - name: Configurar Java en el servidor
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar e Instalar Flutter SDK (Actualizado a 3.24.0)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      - name: Configurar Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar Flet y dependencias del sistema
        run: |
          python -m pip install --upgrade pip
          pip install "flet[cli]"
          pip install -r requirements.txt

      - name: Traducir codigo y Compilar APK Nativo (Con confirmacion automatica)
        run: |
          flet build apk --python-version 3.12 --yes

      - name: Subir Archivo APK para Descarga Directa
        uses: actions/upload-artifact@v4
        with:
          name: AppBombeo_Instalable_Android
          path: build/apk/*.apk
